### ISSUE TITLE
Failed to run "HSAIPCTest.SetSystemMemory"

### ISSUE THREAD

**Issue by andyzhanged** [RadeonOpenCompute/ROCT-Thunk-Interface#55]
Hi,
I failed to  run /hsatest --gtest_filter="HSAIPCTest.SetSystemMemory", then i debug and found the reason is that parent process export system memory to  child process failed. The libhsakmt.so.1 library is from roc-3.1.x, but the test will pass if i use the libhsakmt.so.1  library before roc-2.8.x branch. So i compare the code between roc-3.1.x with roc-2.7.x, found the difference as follow:

```
branch 2.7.x
/* If HSA_USERPTR_FOR_PAGED_MEM is set to a non-0 value,
enable userptr for all paged memory allocations
*/
pagedUserptr = getenv("HSA_USERPTR_FOR_PAGED_MEM");
svm.userptr_for_paged_mem = (pagedUserptr && strcmp(pagedUserptr, "0"));
 
branch 3.1.x
/* If HSA_USERPTR_FOR_PAGED_MEM is not set or set to a non-0
* value, enable userptr for all paged memory allocations
*/
pagedUserptr = getenv("HSA_USERPTR_FOR_PAGED_MEM");
svm.userptr_for_paged_mem = (!pagedUserptr || strcmp(pagedUserptr, "0"));
```
The usage of HSA_USERPTR_FOR_PAGED_MEM has been changed, So the test will malloc system memory with the flag KFD_IOC_ALLOC_MEM_FLAGS_USERPTR. Before this change,  the test will malloc system memory with the flag KFD_IOC_ALLOC_MEM_FLAGS_GTT and the test can pass. 
So why we change the usage of HSA_USERPTR_FOR_PAGED_MEM? 

Thanks.

**Comment by kentrussell** [comment]
You can use the "blame" function to see who made changes related to a specific line in a file (in this case, src/fmm.c). The patch in question is "libhsakmt: Enable HSA_USERPTR_FOR_PAGED_MEM by default" 

The comments also indicate the change in functionality. Instead of disabling USERPTR by default unless overridden by the user, we enable it by default unless overridden by the user.

**Comment by fxkamd** [comment]
The change to use userptr for system memory had multiple reasons motivating it, related to memory usage limitations and NUMA performance issues:

- Use unpinned user mode memory rather than pinned kernel memory allocated by TTM
- Remove dependency TTM pinned system memory usage limits
- Allow controlling NUMA affinity of system memory allocations

The IPC APIs in HIP are only required to support VRAM. I'm not sure why there is a system memory IPC test in hsatest.

**Comment by andyzhanged** [comment]
Hi,kentrussell and fxkamd, thanks you for your reply. I have figure out this issue.
