### ISSUE TITLE
The overhead of dispatching NOOP kernel

### ISSUE THREAD

**Issue by lscat11** [RadeonOpenCompute/ROCT-Thunk-Interface#66]
Hi, as ROCm leverages doorbells to implement user-mode kernel dispatching, I was wondering if there were significant hardware "startup" overhead after writing to the doorbell. 

For example, when I dispatch a NOOP kernel a million times, it could be done in two ways:
1. Dispatch them one by one, i.e. a million times doorbell writing, and each one is followed by a polling on the completion signal.
2. Dispatch them in batch, i.e. writing the doorbell once for a batch and polling the completion signal of the last one.

So, leaving aside the completion signal and interrupt handler, would the first way incur more hardware "startup" overhead than another, or they are essentially the same excepting for some subtle details, such as DMA overhead, cache utilization?

**Comment by fxkamd** [comment]
I'm not an expert for the hardware and firmware involved here. But my basic understanding is, that #1 will be slower because your CPU thread submitting the work will wait for each completion and let the GPU go idle for a short time before the next job is submitted. You're serializing everything and preventing any latency hiding or concurrency between CPU and GPU. The fastest solution would be #3 where you ring the doorbell after each dispatch submission but don't wait for completion until you submitted the last one. That way the GPU can start working after the first dispatch was submitted and then work concurrently with the CPU while the CPU writes and submits more dispatches into the queue.

There is some overhead starting a new dispatch in the MEC firmware for handling command submissions and AQL packet parsing. Then there is more overhead for creating wavefronts and sending them to available compute units, and signaling their completion back to the CP so it can send the completion signal to the host. There is also and some latency getting the completion signal back to the host. For short waits, the CPU will poll, so at least you shouldn't get the latency of sleeping and waking up your CPU thread from an interrupt handler. I don't know how the total overhead breaks down between all of those.
