### ISSUE TITLE
Wrong rpm dep?

### ISSUE THREAD

**Issue by ckoehler** [RadeonOpenCompute/ROCT-Thunk-Interface#73]
I don't think a package named `libdrm-amdgpu` exists in Centos7. There is `libdrm`, which also provides a `libdrm_amdgpu.so.1()(64bit)` file.

We are seeing this error:

```
Error: Package: hsakmt-roct-devel-20211222.1.5.50000-49.el7.x86_64 (ROCm)
           Requires: libdrm-amdgpu
```

So should it be `libdrm` instead?

**Comment by kentrussell** [comment]
libdrm-amdgpu is provided in CentOS as part of the ROCm stack. This is why we have it covered in the CMakeLists.txt file with:

# NOTE: CentOS/RHEL <8 and SUSE <10 do not have support for rpm recommends,
# so HSAKMT_REQUIRES_LIBDRM should be defined when building EL7 to avoid
# producing binaries which do not install on CentOS7 or RHEL7
if(HSAKMT_REQUIRES_LIBDRM)
  string ( APPEND CPACK_RPM_PACKAGE_REQUIRES ", libdrm-amdgpu" )
else()
  set(CPACK_RPM_PACKAGE_RECOMMENDS "libdrm-amdgpu" )
endif()
(https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/master/CMakeLists.txt#L364)

You can remove this if you are trying to build the thunk manually, but we have the recommends for CentOS/RHEL 8. But since "recommends" doesn't exist in the rpm application provided in CentOS/RHEL 7, we have this workaround. 
So yes, we mean the libdrm-amdgpu library. This is provided by AMD through the ROCm and amdgpu-pro releases. If you don't intend to distribute the grab the libdrm-amdgpu package, you can just remove the code above and skip the dependency.

Note that the libdrm requirement is covered at the line above, where we require libdrm-devel . libdrm-amdgpu is for providing accurate Marketing Names for the products, so it's not a hard requirement (hence RECOMMENDS for distros that support that packaging tag)

**Comment by ckoehler** [comment]
Thanks, not trying to build, just install, and for some reason `libdrm-amdgpu` isn't pulled in. What repo does it belong to? We are using this one, and it doesn't have that package: `http://repo.radeon.com/rocm/yum/rpm/`

**Comment by ckoehler** [comment]
Looks like using `http://repo.radeon.com/rocm/yum/4.2/` (for our rocm version) does the trick.

**Comment by kentrussell** [comment]
The alignment between ROCm and amdgpu-pro is going to make more sense in 2022.
For 4.5, the corresponding release for amdgpu-pro is 21.40
For 5.0, the corresponding release for amdgpu-pro is 21.50

The amdgpu-install tool is supposed to be able to grab those packages by default. So for CentOS7, you'd use:
ROCm 5.0.*: https://repo.radeon.com/amdgpu/21.50/rhel/7.9/main/x86_64/
ROCm 4.5.*: https://repo.radeon.com/amdgpu/21.40/rhel/7.9/main/x86_64/

And inside there, you can find the libdrm-amdgpu package we reference. Again, this should get a whole lot cleaner once we get to 5.1. 4.5.x was the first release where we fully aligned our stacks . Note that 4.2 didn't have this recommends/requires dependency, as that was brought in for 4.3.x (IIRC). And the only issue is that the "Marketing Name" field inside apps like rocminfo won't be populated. So you can also just tell it to get by and to ignore dependencies. Or you can use the repos above. Or you can use the amdgpu-install utility and hope that it grabs the right repos. At least we have a few options to get you going.
