### ISSUE TITLE
Issue with new device id support

### ISSUE THREAD

**Issue by FalconBsp** [RadeonOpenCompute/ROCT-Thunk-Interface#9]
Ideally user space should request or read via sysfs entry or ioctl to know the present driver properties. But we have seen ROCT-Thunk using device ids with in the code.

For example :
1) OCT-Thunk-Interface/blob/master/src/topology.c  contains  gfxip_lookup_table . IS it possible to avoid the dependency in user space and get the details from kernel driver?

2) ROCT-Thunk-Interface/blob/master/src/queues.c  contains struct device_id supported_devices[] = {.
Is it possible to avoid the dependency in user space and get the details from kernel driver?

**Comment by gstoner** [comment]
I talking to the team about this, it lead me down another path but with fix I am looking for this will get cleaned up in the future.

**Comment by fxkamd** [comment]
It doesn't make sense for us to consolidate all the device info in the kernel. The information that's currently in user mode tables is there because the kernel doesn't use it itself and the kernel is not involved in getting the information from the HW or firmware. For example things like GFX IP major, minor and stepping versions are a pure software construct that's required by the compiler and ROCr Runtime and defined in the Thunk API spec. Performance counter tables are meaningless for KFD also.

We are reducing some of the duplication in the Thunk where we currently have multiple device ID tables. That means adding a new device ID only needs to change one place in the Thunk. However we still need at least one device ID table in user mode (in the Thunk).

**Comment by gstoner** [comment]
Thanks @fxkamd   we close this now.
